
development:
  adapter: postgresql
  encoding: unicode
  database: numbeers-dev
  pool: 5
  host: localhost
  username: nitrous
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: numbeers-test
  pool: 5
  host: localhost
  username: nitrous
  password:

production:
  adapter: postgresql
  database: numbeers
  pool: 5
  password: postgres